@startuml pert9
autonumber "<b> ."
actor user 
participant "Menu" as M
participant "Pilih Menu" as pil 
participant "Aku" as A 
participant "Dia" as D 
participant "Quantity" as qty
participant "Total" as tot 
participant "Exit" as X

user --> M Tampilkan Menu Utama 
M --> pil: Pilih Menu 1 atau 2, Pilih Dia atau Aku
pil --> A: Menampilkan profile Aku
A--> qty: Masukan Jumlah Quantity
qty--> tot: Print
M <-- tot: Kembali ke Menu
pil --> D: Menampilkan profile Dia
D--> qty: Masukan Jumlah Quantity
qty--> tot: Print
tot --> X: Jika Pilihan Exit
M <--tot : Kembali ke Menu

@enduml